name:                bnf
version:             0.1.0.0
github:              "nabechan777/bnf"
license:             BSD3
author:              "DaikiWatanabe"
maintainer:          "daiki7watanabe@gmail.com"
copyright:           "2019 DaikiWatanabe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nabechan777/bnf#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec
- text
- resourcet
- conduit
- conduit-extra

library:
  source-dirs: src

executables:
  bnf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bnf

tests:
  bnf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bnf
    - hspec
