name:                AtCoder
version:             0.1.0.0
github:              "nabechan777/AtCoder"
license:             BSD3
author:              "DaikiWatanabe"
maintainer:          "daiki7watanabe@gmail.com"
copyright:           "2018 DaikiWatanabe"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nabechan777/AtCoder#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  AtCoder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AtCoder

tests:
  AtCoder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AtCoder
